pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.npm-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  install:
    image: node:alpine
    commands:
      - node -v
      - npm -v
      - npm config set cache-folder .npm-cache
      - npm install --pure-lockfile
  publish:
    image: plugins/docker
    repo: drone/node-demo
    secrets: [ Account-docker-hub, Password-docker-hub]
    dry_run: true # remove this to publish
