
kind: pipeline
type: docker
name: default

steps:
- name: Install package
  image: node:alpine
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - npm config set cache-folder .npm-cache
  - npm install

- name: Run Images
  image: appleboy/drone-ssh
  settings:
    host: drone.e-tutor.wtf
    port: 22
    command_timeout: 6m
    username: fbeta
    password:
      from_secret: server_password
    script:
      - echo ${Test-env}
  when:
    branch:
      - master
    event:
      - push
    status:
      - success
volumes:
  - name: cache
    host:
      path: /var/lib/cache