
kind: pipeline
type: docker
name: default

steps:
- name: Run Images
  image: appleboy/drone-ssh
  environment:
    test1:
      from_secret: Test-env
  settings:
    host: drone.e-tutor.wtf
    port: 22
    command_timeout: 6m
    username: fbeta
    password:
      from_secret: server_password
    script:
      - "echo ${Test-env}"
  when:
    branch:
      - master
    event:
      - push
    status:
      - success
volumes:
  - name: cache
    host:
      path: /var/lib/cache