kind: pipeline
name: default

steps:
- name: Install
  image: node:alpine
  commands:
    - node -v
    - npm -v
    - npm config set cache-folder .npm-cache
    - npm install
- name: Purplish
  image: plugins/docker
  repo: tungduy/drone-demo
  dockerfile: Dockerfile
  secrets: [ docker_username, docker_password ]
  tags:
    - ${DRONE_BRANCH}-latest

