kind: pipeline
name: default

steps:
- name: Install
  image: node:alpine
  commands:
    - node -v
    - npm -v
    - npm config set cache-folder .npm-cache
    - npm install
- name: Publish
  image: plugins/docker
  settings:
    auto_tag: true
    repo: tungduy/drone-demo
    dockerfile: Dockerfile
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
  
- name: slack_build
  image: plugins/slack
  settings:
    webhook: 'https://hooks.slack.com/services/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'
    channel: drone-notify
    username: drone
    icon_emoji: ':hammer:'
    template: >
      <{{build.link}}|Build {{build.number}}> ở {{build.branch}} *{{build.status}}*
  when:
    status:
      - success
      - failure