
kind: pipeline
type: docker
name: default

steps:
- name: Copy files
  image: appleboy/drone-scp
  settings:
    host: drone.e-tutor.wtf
    port: 22
    username: fbeta
    password:
      from_secret: server_password
    target:  ~/project/e-tutor/${DRONE_REPO_NAME}
    strip_components: 1
    source:
      - docker-compose.yml
  when:
    branch: master
- name: Run Images
  image: appleboy/drone-ssh
  environment:
    TOKEN:
      from_secret: Test-env
  settings:
    host: drone.e-tutor.wtf
    port: 22
    command_timeout: 6m
    username: fbeta
    password:
      from_secret: server_password
    script:
      - echo $TOKEN
      - echo ${TOKEN}
      - cat ~/project/e-tutor/${DRONE_REPO_NAME}/docker-compose.yml
  when:
    branch:
      - master
    event:
      - push
    status:
      - success
volumes:
  - name: cache
    host:
      path: /var/lib/cache