kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.npm-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
  - name: Install
    image: node:alpine
    commands:
      - node -v
      - npm -v
      - npm install --pure-lockfile
  - publish:
    image: plugins/docker
    repo: tungduy/drone-demo
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    tags: [ latest, 1.1 ]
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.npm-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
    when:
      branch: master
  